// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izllymzoykgutsygfwwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6bGx5bXpveWtndXRzeWdmd3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTk4NzEsImV4cCI6MjA1NzIzNTg3MX0.SQRK0eVOxBQbpxsFhn3JHIvytCepfzEl9gu1I07ItkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);